version: '2'
services:
  unms:
    image: nico640/docker-unms:1.4.4
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "2055:2055/udp"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ../../environment/dev:/config